#define SECHUD_NT_CREWTRAINER "hudnanotrasencrewtrainer"
//Interdyne Research Base Ruin
#define SECHUD_INTERDYNE_CHEMIST "hud_interdynechemist"
#define SECHUD_INTERDYNE_GENETICIST "hud_interdynegeneticist"
#define SECHUD_INTERDYNE_CMO "hud_interdynecmo"
#define SECHUD_INTERDYNE_CARGO "hud_interdynecargo"
//Forgottenship Ruin
#define SECHUD_GORLEX_CREWMAN "hud_gmcrewman"
#define SECHUD_GORLEX_OPERATIVE "hud_gmoperative"
#define SECHUD_GORLEX_WRECKER "hud_gmwrecker"
#define SECHUD_GORLEX_MECHANIC "hud_gmmechanic"
#define SECHUD_GORLEX_MEDICALDOCTOR "hud_gmmedicaldoctor"
#define SECHUD_GORLEX_SHUTTLEPILOT "hud_gmshuttlepilot"
#define SECHUD_GORLEX_ENSIGN "hud_gmensign"
#define SECHUD_GORLEX_FOREMAN "hud_gmforeman"
#define SECHUD_GORLEX_LIEUTENANT "hud_gmlieutenant"
#define SECHUD_GORLEX_CAPTAIN "hud_gmcaptain"
